env:
  TZ: Asia/Ho_Chi_Minh

task:
  name: "Lumi Builds"
  timeout_in: 120m  
  container:
      image: ubuntu:latest
      cpu: 7
      memory: 28G
  
  Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - apt update -y && apt install git bc bison build-essential ccache flex lib32ncurses5-dev lib32readline-dev lib32z1-dev curl wget rsync zip unzip lzma cpio neofetch libc6-dev-i386 libncurses5-dev libncurses5 -y
       - apt install python-is-python3 -y
       - git config --global user.name "HoangLong-Lumi"
       - git config --global user.email "adasdhbjwqbekjqwhe@gmail.com"
       - ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""

  Sync_script:
       - mkdir $HOME/bin
       - curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/bin/repo
       - chmod a+x $HOME/bin/repo
       - export PATH="$PATH:$HOME/bin"
       - mkdir ~/Lineage ~/LineageCCache
       - cd ~/Lineage
       - repo init --depth=1 --no-repo-verify -u https://github.com/HoangLong-Lumi/android.git -b lineage-17.1 -g default,-mips,-darwin,-notdefault
       - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j24 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j24
       - git clone https://github.com/almondnguyen/android_kernel_samsung_grandppltedx --depth=1 -b lineage-15.1 kernel/samsung/grandppltedx
       - git clone https://github.com/almondnguyen/android_device_samsung_grandppltedx --depth=1 -b lineage-17.1 device/samsung/grandppltedx
       - git clone https://github.com/almondnguyen/android_vendor_samsung_grandppltedx --depth=1 -b lineage-16.0 vendor/samsung/grandppltedx

  Build_script:
       - cd ~/Lineage
       - export PATH="$PATH:$HOME/bin"
       - export ALLOW_MISSING_DEPENDENCIES=true
       - export CCACHE_DIR=~/LineageCCache/cache
       - export CCACHE_EXEC=$(which ccache)
       - export USE_CCACHE=1
       - ccache -M 20G
       - ccache -o compression=true
       - ccache -z
       - . build/envsetup.sh
       - lunch lineage_grandppltedx-userdebug
       - make bacon -j5

  Upload_build_script:
       - cd ~/Lineage/out/target/product/grandppltedx
       - curl -sL https://git.io/file-transfer | sh
       - ./transfer anon lineage-17.1-*-grandppltedx.zip
